version: '3.6'
services:
  telegraf:
    image: telegraf:1.11-alpine
    volumes:
    - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - '8125:8125/udp'
    restart: always

  influxdb:
    image: influxdb:1.7-alpine
    env_file: configuration.env
    ports:
      - '8086:8086'
    restart: always
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:6.3.3
    depends_on:
      - influxdb
    env_file: configuration.env
    links:
      - influxdb
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/

volumes:
  grafana_data: {}
  influxdb_data: {}
